language: ruby
sudo: false

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 993c591cad267ef69e64e6147baee06483d935dd4741948c2ad85d09b20695bd

install:
  - bundle install

script:
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter
