language: ruby
sudo: false

branches:
  only:
    - master

addons:
    code_climate:
        repo_token: ENV['CODECLIMATE_REPO_TOKEN']

install:
  - bundle install

script:
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter
